#!/bin/bash

FOLDER_ID=b3ebe16f-52ad-4f44-89d6-ac39017ef692

SEARCH=envwarden

usage()
{
    echo "envwarden: use Bitwarden to manage server secrets"
    echo ""
    echo "Get your secure environment variables from Bitwarden onto your server."
    echo "envwarden searches your Bitwarden vault for items matching"
    echo "a search criteria (defaults to 'envwarden')."
    echo "Then it goes through all custom fields on every item found"
    echo "and make them available as envirnoment variables."
    echo ""
    echo "Usage: envwarden [--help] [--search] [--dotenv] [--copy]"
    echo ""
    echo "To export environment variables, use: \`eval \$(envwarden)\`"
    echo "To create an .env file, use: \`envwarden --dotenv > .env\`"
    echo ""
    echo "Options:"
    echo -e "\t-h --help"
    echo -e "\t-s --search <keyword> (optional) define the search term for bitwarden items (defaults to $SEARCH)"
    echo -e "\t-d --dotenv (optional) outputs secrets to stdout in .env format"
    echo -e "\t-k --dotenv-docker (optional) outputs secrets to stdout in a \"docker-friendly\" .env format (no quotes)"
    echo -e "\t-c --copy <destination folder> (optional) copies all attachments on the item to a folder"
    echo ""
    echo "You can use ~/.envwarden to store your credentials (just email, or email:password)"
}

while [[ $# > 0 ]]; do
    key="$1"
    case $key in
        -h | --help)
            usage
            exit
            ;;
        -d | --dotenv)
            DOTENV=true
            ;;
        -k | --dotenv-docker)
            DOTENV_DOCKER=true
            ;;
        -s | --search)
            SEARCH=$2
            shift
            ;;
        -c | --copy)
            COPY_TO=$2
            COPY_TO=${COPY_TO:=.}
            shift
            ;;
        *)
            echo "ERROR: unknown parameter \"$PARAM\""
            usage
            exit 1
            ;;
    esac
    shift
done

bw_hits="$(bw-session list items --folderid "$FOLDER_ID" --search "$SEARCH")"

while read -r key; do
    read -r value
    if [[ -n "$DOTENV" ]]; then
        echo $key=\"$value\"
    elif [[ -n "$DOTENV_DOCKER" ]]; then
        echo $key=$value
    else
        # wrap keys and values in single quotes to avoid further interpolation,
        # plus sanitize for single quote symbols to avoid command injection
        quoted_key="$(echo "$key" | sed "s/'/'\"'\"'/g")"
        quoted_value="$(echo "$value" | sed "s/'/'\"'\"'/g")"
        echo export \'$quoted_key\'=\'$quoted_value\'
    fi
done < <(echo "$bw_hits"|jq -r '.[].fields[]? | select(.name != null) | select(.value != null) | .name, .value')

notes="$(echo "$bw_hits"|jq -r '.[].notes')"
if [[ -n "$notes" && "$notes" != "null" ]]; then
  echo "$(echo "$notes" | grep -v '^#' | sed 's/^/export /')"
fi

if [[ -n "$COPY_TO" ]]; then
    item_id=$(bw-session list items --folderid "$FOLDER_ID" --search "$SEARCH" |jq -r '.[].id')
    if [[ -n "$item_id" ]]; then
        while read -r attachment_id; do
            read -r filename
            bw-session get attachment $attachment_id --itemid $item_id --output "$COPY_TO/$filename" 1>&2
        done < <(bw-session list items --folderid "$FOLDER_ID" --search "$SEARCH" |jq -r '.[].attachments[] | .id, .fileName')
    fi
fi
